[package]
name = "youtube-queuer"
version = "0.1.0"
authors = ["Simon Walker <s.r.walker101@googlemail.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11.26"
tokio-core = "0.1.17"
structopt = "0.2.8"
